.PHONY : clean all

all :
	cd java; make
	cd c; make
	cd go; make
	cd python; make
	cd cpp; make



clean :
	cd java; make clean
	cd c; make clean
	cd go; make clean
	cd python; make clean
	cd cpp; make clean
